CREATE TABLE Person(
                       id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       full_name varchar(100) NOT NULL UNIQUE,
                       year_of_birth int NOT NULL
);

CREATE TABLE Book(
                     id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                     title varchar(100) NOT NULL,
                     author varchar(100) NOT NULL,
                     year int NOT NULL,
                     person_id int REFERENCES Person(id) ON DELETE SET NULL,
                    taken_at TIMESTAMP
);

INSERT INTO Person(full_name, year_of_birth) values ('Ivanov I.I.', 1987);
INSERT INTO Person (full_name, year_of_birth) values ('Petrov P.P.', 1965);
INSERT INTO Person (full_name, year_of_birth) values ('Sidorov S.S.', 1973);
INSERT INTO Person (full_name, year_of_birth) values ('Nikolaev N.N.', 1981);
INSERT INTO Person (full_name, year_of_birth) values ('Aleksandrov A.A.', 1990);

INSERT INTO Book(title, author, year) VALUES ('War and Peace', 'Leo Tolstoy', 1869);
INSERT INTO Book (title, author, year) VALUES ('On Liberty', 'John Stuart Mill', 1959);
INSERT INTO Book (title, author, year) VALUES ('Middlemarch', 'George Eliot', 1871);
INSERT INTO Book (title, author, year) VALUES ('Nineteen Eighty-Four', 'George Orwell', 1949);
INSERT INTO Book (title, author, year) VALUES ('The Road', 'Cormac McCarthy', 2006);
INSERT INTO Book (title, author, year) VALUES ('Jane Eyre', 'Charlotte Bronte', 1847);